<?php
if(isset($_GET['id']) && $_GET['id']!="")
{
    $page_no=$_GET['id'];
}else{
    $page_no=1;
}
$con=mysqli_connect('','polaznik13','polaznik1770','polaznik13');
$result_count=mysqli_query(
    $con,
    "SELECT COUNT(mov_id) As total FROM movie"
);
$total_records_per_page=3;
$total_records=mysqli_fetch_array($result_count);
$total_records=$total_records['total'];
$total_no_of_pages=ceil($total_records/$total_records_per_page);
$offset=($page_no-1)* $total_records_per_page;
$previous_page=$page_no-1;
$next_page=$page_no+1;
$second_last=$total_no_of_pages-1;
$adjacents="1";
?>
<div>
    <strong><?php echo $page_no." of ".$total_no_of_pages; ?></strong>
</div>
<nav class="pagination is-centered">

<ul class="pagination-list">
    <?php if($page_no>1){
        echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=1'>First Page</a></li>";
    } ?>
    <li <?php if($page_no <= 1){} ?>>
        <a class="pagination-link" <?php if ($page_no>1){
            echo "href='/~polaznik13/browse/page?id=$previous_page'";
        } ?>> Previous</a>
    </li>
    <?php if ($total_no_of_pages <=10){
        for ($counter=1;$counter<=$total_no_of_pages; $counter++){
            if($counter == $page_no)
            {
                echo "<li class='active'><a class='pagination-link'>$counter</a></li>";
            }else{
                echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=$counter'>$counter</a></li>";
            }
        }
    } elseif ($total_no_of_pages>10){
        if ($page_no <=4){
            for ($counter=1;$counter<8;$counter++){
                if ($counter==$page_no){
                    echo "<li ><a class='pagination-link'>$counter</a></li>";
                }else{
                    echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=$counter'>$counter</a></li>";
                }
            }
            echo "<li><a class='pagination-link'>...</a>";
            echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=$total_no_of_pages'>$total_no_of_pages</a></li>";
        }elseif($page_no>4 && $page_no < $total_no_of_pages -4){
            echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=1'>1</a></li>";
            echo "<li><a class='pagination-link'>...</a></li>";
            for ($counter=$page_no-$adjacents;$counter<=$page_no+$adjacents;$counter++){
                if ($counter==$page_no){
                    echo "<li class='pagination-link'><a>$counter</a></li>";
                }else
                {
                    echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=$counter'>$counter</a></li>";
                }
            }
            echo "<li><a class='pagination-link'>...</a>";
            echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=$total_no_of_pages'>$total_no_of_pages</a></li>";
        } else {
            echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=1'>1</a></li>";
            echo "<li><a class='pagination-link'>...</a></li>";
            for ($counter=$total_no_of_pages-6;$counter<=$total_no_of_pages;$counter++)
            {
                if ($counter==$page_no){
                    echo "<li><a class='pagination-link'>$counter</a></li>";
                }else{
                    echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=$counter'>$counter</a></li>";
                }
            }
        }
    }
    ?>
    <li <?php if($page_no >= $total_no_of_pages){echo "";} ?>>
        <a class='pagination-link' <?php if ($page_no<$total_no_of_pages){
            echo "href='/~polaznik13/browse/page?id=$next_page'";
        } ?>> Next</a>
    </li>
    <?php if ($page_no<$total_no_of_pages){
        echo "<li><a class='pagination-link' href='/~polaznik13/browse/page?id=$total_no_of_pages'>Last</a></li>";
    }?>
</ul>
</nav>
