<?php include 'layout/header.phtml' ?>
    <br><h1 class="title has-text-primary-light has-background-dark">Your account</h1>
    <div class="section">
    <p class="subtitle">Name: <?= $currentUser->getFirstName() ?> <?= $currentUser->getLastName() ?></p>
    <p class="subtitle">Email:  <?= $currentUser->getEmail() ?></p>
</div>
<p class="subtitle has-text-primary-light has-background-dark">Your watchlist:</p>
<div class="columns is-multiple">
<?php foreach ($movie_watchlist as $watchlist): ?>
    <div class="column is-narrow">
    <img src="/images/<?=$watchlist->getMov_id()?>.jpg" width="90" height="134">
    <a href="/~polaznik13/review/details?id=<?= $watchlist->getMov_id() ?>">
    <p><?= $watchlist->getMov_title() ?></p>
    </a>
    <a href="/~polaznik13/review/deleteFrom?id=<?= $watchlist->getMov_id() ?>">Delete</a>
    </div>
<?php endforeach; ?>
</div>
<div class="section">
    <form class="field" action="change" method="post">
        <label class="label" for="pass">Enter your password: </label>
        <input class="input" type="password" id="pass" name="pass" required>
        <label class="label" for="new_pass">Enter your new password: </label>
        <input class="input" type="password" id="new_pass" name="new_pass" required>
        <label class="label" for="confirm_new_pass">Confirm your new password: </label>
        <input class="input" type="password" id="confirm_new_pass" name="confirm_new_pass" required>
        <input type="hidden" value="<?=$currentUser->getId() ?>" name="id">
        <input class="button" type="submit" value="Update">
    </form>
</div>
<?php include 'layout/footer.phtml' ?>