<?php include 'layout/header.phtml' ?>
    <div>
        <h1 class="title"><?=$movie->getMov_title() ?>  </h1>
        <iframe width="560" height="315" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen src="<?=$movie->getMov_trailer() ?>"></iframe>
        <h2 class="subtitle">Movie description:</h2>
        <p><?=$movie->getMov_desc() ?></p>
        <p>Movie Rating: <?=$movie->getMov_rating() ?>  </p>
        <p>Release date: <?=$movie->getMov_year() ?>  </p>
        <p>Movie length: <?=$movie->getMov_time() ?> min </p>
    </div>
    <p class="subtitle has-text-primary-light has-background-dark">Directors:</p>
<div class="columns">
    <?php foreach ($director as $dir): ?>
        <div class="column is-narrow ">
            <p><strong><?= $dir->getDir_fname() ?>  <?= $dir->getDir_lname() ?></strong></p>
        </div>
    <?php endforeach; ?>
</div>
<p class="subtitle has-text-primary-light has-background-dark">Genres:</p>
<div class="columns">
    <?php foreach ($movie_genres as $gen): ?>
        <div class="column is-narrow ">
            <p><strong><?= $gen->getGenre() ?></strong></p>
        </div>
    <?php endforeach; ?>
</div>
    <p class="subtitle has-text-primary-light has-background-dark">Actors and roles: </p>
<div class="columns">
<?php foreach ($actor as $cast): ?>
        <div class="column is-narrow ">
                <p><strong><?= $cast->getAct_fname() ?>  <?= $cast->getAct_lname() ?></strong></p>
                <p><?= $cast->getRole() ?></p>
        </div>
<?php endforeach; ?>
</div>
    <br>
<h2 class="subtitle has-text-primary-light has-background-dark">Reviews:</h2>
<?php foreach ($review as $reviews): ?>
            <div class="section">
                <div class="container ">
                    <h1><?= $reviews->getRev_name() ?></h1><br>
                    <p><?= $reviews->getRev_content() ?></p>
                    <p>Review score: <?= $reviews->getRev_score() ?></p>
                    <?php if ($currentUser): ?>
                    <form method="post" action="up">
                        <input type="hidden" name="mov_id" value="<?= $reviews->getRev_mov_id() ?>" >
                    <input class="button" type="submit" name="id" value="<?= $reviews->getRev_id() ?>">
                    </form>

                    <form method="post" action="down">
                        <input type="hidden" name="mov_id" value="<?= $reviews->getRev_mov_id() ?>" >
                        <input class="button" type="submit" name="id" value="<?= $reviews->getRev_id() ?>">
                    </form>
                    <?php endif; ?>
                    <p>Score: <?= $reviews->getRev_up()- abs($reviews->getRev_down()) ?></p>
                </div>
            </div>
<?php endforeach; ?>

<?php if ($currentUser): ?>
        <form method="post" action="create">
            <div class="field">
                <label class="label" for="new_review">What did you think of the movie</label>
                <textarea class="textarea" id="new_review" name="new_review" rows="3"></textarea>
                <input class="hidden" type="hidden"  id="mov_id" name="mov_id" value="<?= $movie->getMov_id() ?>">
                <p class="label">Score: </p>
                <label for="review_rating">1</label>
                <input  type="radio" id="1" name="review_rating" value="1">
                <label for="review_rating">2</label>
                <input type="radio" id="2" name="review_rating" value="2">
                <label for="review_rating">3</label>
                <input type="radio" id="3" name="review_rating" value="3">
                <label for="review_rating">4</label>
                <input type="radio" id="4" name="review_rating" value="4">
                <label for="review_rating">5</label>
                <input type="radio" id="5" name="review_rating" value="5"><br>
                <button type="submit" class="btn btn-primary">Review</button>
            </div>
        </form>
<?php endif; ?>
<?php include 'layout/footer.phtml' ?>