<?php include 'layout/header.phtml' ?>
    <div class="">
        <h1 class="title"><?=$movie->getMov_title() ?>  </h1>
        <?php if ($currentUser): ?>
            <form method="post" action="/~polaznik13/addTo">
                <input type="hidden" name="mov_title" value="<?= $movie->getMov_title() ?>">
                <input type="hidden" name="mov_id" value="<?= $movie->getMov_id() ?>">
                <input type="hidden" name="id" value="<?= $currentUser->getId() ?>">
                <input class="button is-primary" type="submit" value="Add to watchlist" >
            </form>
        <?php endif; ?>
        <iframe width="560" height="315" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen src="<?=$movie->getMov_trailer() ?>"></iframe>
        <h2 class="subtitle">Movie description:</h2>
        <p><?=$movie->getMov_desc() ?></p>
        <p>Movie Rating: <?=$movie->getMov_rating() ?>  </p>
        <p>Release date: <?=$movie->getMov_year() ?>  </p>
        <p>Movie length: <?=$movie->getMov_time() ?> min </p>
    </div>
<p class="subtitle has-text-primary-light has-background-dark">Directors:</p>
<div class="columns" style="overflow-x:auto">
    <?php foreach ($director as $dir): ?>
        <div class="column is-narrow ">
            <p><strong><?= $dir->getDir_fname() ?>  <?= $dir->getDir_lname() ?></strong></p>
        </div>
    <?php endforeach; ?>
</div>
<p class="subtitle has-text-primary-light has-background-dark">Genres:</p>
<div class="columns">
    <?php foreach ($movie_genres as $gen): ?>
        <div class="column is-narrow ">
            <span class="tag is-medium"><strong><?= $gen->getGenre() ?></strong></span>
        </div>
    <?php endforeach; ?>
</div>
    <p class="subtitle has-text-primary-light has-background-dark">Actors and roles: </p>
<div class="columns">
<?php foreach ($actor as $cast): ?>
        <div class="column is-narrow ">
            <div class="box">
                <p class="subtitle"><strong><?= $cast->getAct_fname() ?>  <?= $cast->getAct_lname() ?></strong></p>
                <p><?= $cast->getRole() ?></p>
            </div>
        </div>
<?php endforeach; ?>
</div>
    <br>

<div class="columns">
    <div class="column">
    <h2 class="subtitle has-text-primary-light has-background-dark">User reviews:</h2>
<?php foreach ($review as $reviews): ?>
            <?php if ($reviews->getUser_type()==1): ?>
            <?php include_once 'userreview.phtml';?>
            <?php endif; ?>
<?php endforeach; ?>
    </div>
<div class="column">
    <h2 class="subtitle has-text-primary-light has-background-dark">Reviewer reviews:</h2>

<?php foreach ($review as $reviews): ?>
    <?php if ($reviews->getUser_type()==2): ?>
        <?php include_once 'reviewerreview.phtml';?>
    <?php endif; ?>
<?php endforeach; ?>
</div>
</div>
<?php if ($currentUser): ?>
        <form method="post" action="/~polaznik13/create">
            <div class="field">
                <label class="label" for="new_review">What did you think of the movie</label>
                <textarea class="textarea" id="new_review" name="new_review" rows="3"></textarea>
                <input class="hidden" type="hidden"  id="mov_id" name="mov_id" value="<?= $movie->getMov_id() ?>">
                <p class="label">Score: </p>
                <label for="review_rating">1</label>
                <input  type="radio" id="1" name="review_rating" value="1" required>
                <label for="review_rating">2</label>
                <input type="radio" id="2" name="review_rating" value="2">
                <label for="review_rating">3</label>
                <input type="radio" id="3" name="review_rating" value="3">
                <label for="review_rating">4</label>
                <input type="radio" id="4" name="review_rating" value="4">
                <label for="review_rating">5</label>
                <input class="radio" type="radio" id="5" name="review_rating" value="5"><br>
                <button type="submit" class="button is-primary">Review</button>
            </div>
        </form>
<?php endif; ?>
<?php include 'layout/footer.phtml' ?>