<?php include 'layout/header.phtml' ?>
<section class="hero is-light">
<div class="hero-body">
    <div class="container">
        <h1 class="title">Movies released this year</h1>
<div class="columns is-multiline">
    <div class="columns " style="overflow-x:auto ">
    <?php foreach ($movie as $post): ?>
    <?php if($post->getMov_year()==2020): ?>
        <div class="column is-narrow">
                <div class="box is-dark">
                    <a href="/~polaznik13/review/details?id=<?= $post->getMov_id() ?>" class="card-link">
                        <img src="/~polaznik13/images/<?=$post->getMov_id()?>.jpg" width="180" height="268">
                        <p class="subtitle"><?= htmlspecialchars($post->getMov_title()) ?></p>
                    </a>
                    <p><?= htmlspecialchars($post->getMov_dt_rel()) ?></p>
                </div>
        </div>
    <?php endif; ?>
    <?php endforeach; ?>
    </div>
</div>
</div>
</section>
<section class="hero is-light">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">All movies  <a href="/~polaznik13/browse/page?id=1" class="tag is-link">See all</a></h1>
    <div class="columns is-multiline">
<?php foreach ($movie as $post): ?>
    <div class="column is-narrow">
        <div>
            <div class="box">
                <a href="/~polaznik13/review/details?id=<?= $post->getMov_id() ?>" class="card-link">
                    <img src="/~polaznik13/images/<?=$post->getMov_id()?>.jpg" width="180" height="268">

                        <p class="subtitle"><?= htmlspecialchars($post->getMov_title()) ?></p>
                    </a>
                    <p><?= htmlspecialchars($post->getMov_dt_rel()) ?></p>
            </div>
        </div>
    </div>
<?php endforeach; ?>
    </div>
</div>
    </div>
</section>
<?php include 'layout/footer.phtml' ?>
