<?php include 'layout/header.phtml' ?>

<hr>
<div class="columns">
    <div class="column is-one-fifth">
    </div>
    <div class="column">
<?php foreach ($movie as $post): ?>
    <div class="block">
        <div>
            <div class="card" style="width: 18rem;">
                <div class="card-body ">
                    <img src="images/<?=$post->getMov_id()?>.jpg" width="180" height="268">
                    <a href="/~polaznik13/review/details?id=<?= $post->getMov_id() ?>" class="card-link">
                        <p><?= htmlspecialchars($post->getMov_title()) ?></p>
                    </a>
                    <p"><?= htmlspecialchars($post->getMov_dt_rel()) ?></p>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
    </div>
</div>
<?php include 'layout/footer.phtml' ?>
