<?php include 'layout/header.phtml' ?>

<form method="post" action="/user/loginSubmit">
    <div class="field">
        <label class="label" for="email">Email</label>
        <input class="input" type="email" class="form-control" id="email" name="email">
        <label class="label" for="password">Password</label>
        <input class="input" type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="button is-primary">Login</button>
</form>

<?php include 'layout/footer.phtml' ?>
