<?php include 'layout/header.phtml' ?>
<div class="field is-grouped is-grouped-centered">
<form style="border-radius: 25px; border: solid dodgerblue; padding: 15px;" method="post" action="/~polaznik13/user/registerSubmit">
        <label class="label" for="first_name">First Name</label>
        <div class="control has-icons-left has-icons-right">
        <input class="input" type="text" class="form-control" id="first_name" name="first_name">
        <span class="icon is-small is-left">
            <i class="fas fa-user"></i>
        </span>
        </div>

        <label class="label" for="last_name">Last Name</label>
        <div class="control has-icons-left has-icons-right">
        <input class="input" type="text" class="form-control" id="last_name" name="last_name">
        <span class="icon is-small is-left">
        <i class="fas fa-user"></i>
        </span>
        </div>

        <label class="label" for="email">Email</label>
        <div class="control has-icons-left has-icons-right">
        <input class="input" type="email" class="form-control" id="email" name="email">
        <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
        </span>
        </div>
        <label class="label" for="password">Password</label>
        <div class="control has-icons-left has-icons-right">
        <input class="input" type="password" class="form-control" id="password" name="password">
        <span class="icon is-small is-left">
        <i class="fas fa-lock"></i>
        </span>
        </div>
        <label class="label" for="confirm_password">Confirm Password</label>
        <input class="input" type="password" class="form-control" id="confirm_password" name="confirm_password" required>
        <p class="label">Select what type of user you are: </p>
        <label class="radio" for="user_type-viewer">Viewer
        <input type="radio" class="radio" id="user_type" name="user_type" value="1" required>
        </label>
        <label class="radio" for="user_type_reviewer">Reviewer
        <input type="radio" class="radio" id="user_type" name="user_type" value="2">
        </label><br>
    <button type="submit" class="button is-link my-2">Register</button>
</form>
</div>
<?php include 'layout/footer.phtml' ?>